name: Bug Report
description: File a bug report
body:
  - type: textarea
    attributes:
      label: Diagnostic
      description: Run `!1pdiagnostic` in Alfred. After the notification/sound, paste into this box
    validations:
      required: true
  - type: textarea
    attributes:
      label: Debugger output
      description: Perform the failing action with [the debugger](https://www.alfredapp.com/help/workflows/advanced/debugger/) open
      render: codeblock
    validations:
      required: true
  - type: textarea
    attributes:
      label: More details
      description: Explain what you did, what happened, and what you expected to happen

